Mvn artifactory 0x01
harness/drone-artifactory pull request #75
Opened 2024-12-18 03:37 UTC by senthilhns

2024-12-18 06:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/drone-artifactory?pullRequest=75) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/drone-artifactory?pullRequest=75) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: senthilhns<br/>:x: senthilnowbfw<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/drone-artifactory?pullRequest=75) it.</sub>

2025-01-06 09:32 UTC, Ompragash requested changes
- Update README wiht a solid example for Jfrog Maven Step
- Test the existing functionalities in Harness CI with the test image to confirm the backward compatibility

2025-01-06 09:34 UTC, Ompragash commented on docker/Dockerfile.windows.amd64.ltsc2022
> +RUN Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.3.6/PowerShell-7.3.6-win-x64.msi -OutFile C:\powershell.msi; `
```suggestion
USER ContainerAdministrator

ENV GODEBUG=netdns=go

RUN Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.3.6/PowerShell-7.3.6-win-x64.msi -OutFile C:\powershell.msi; `
```

2025-01-07 06:24 UTC, senthilhns commented
> * Update README wiht a solid example for Jfrog Maven Step
> * Test the existing functionalities in Harness CI with the test image to confirm the backward compatibility

Updated the README, windoes docker files.
Backward compatibility tests passed for both password and access token here
https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/all/orgs/default/projects/jenkinstoharness/pipelines/jfrog_artifactory_maven_build_publish_senthil_2025_01_07_backward_compatibility/executions/1pl1q-JYT_Ko8v46GE8d7Q/pipeline?storeType=INLINE

2025-01-10 14:20 UTC, Ompragash submitted a review, later dismissed

2025-01-10 14:20 UTC, Ompragash commented on .gitignore
> +drone-artifactory
```suggestion
```

2025-01-10 16:05 UTC, Ompragash approved these changes

2025-01-10 16:05 UTC, merged